services:
  db:
    image: mariadb:11.1
    container_name: db
    env_file:
      - ./db/root.env
    volumes:
      - ./db/sql/:/docker-entrypoint-initdb.d/
      - ./db/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf:ro
      - taptapdb_backup:/var/lib/mysql
    networks:
      db_net:
        ipv4_address: 172.20.0.3

  backend:
    build: backend
    container_name: backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "3000:3000"
    networks:
      db_net:
        ipv4_address: 172.20.0.2

  frontend:
    image: nginx:stable
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - /var/log/nginx/:/var/log/nginx/
      - /etc/letsencrypt:/etc/letsencrypt




networks:
  db_net:
    name: db_net
    external: true

volumes:
  taptapdb_backup:
    external: true
